### ISSUE TITLE
Proposal:  An efficient repo management for FauxPilot community

### ISSUE THREAD

**Issue by leemgs** [fauxpilot/fauxpilot#103]
Hello. I would like to suggest the **org/account** name of this project for stable maintenance of FauxPilot and more efficient operation of the repo.

As we all know, since the FauxPilot project is being developed as a Free/Opensource Copilot project, many people around the world are very interested. Therefore, it is likely that maintenance will be more efficient if we create a more appropriate **org/account** name than your current personal account (account name). As many other open source projects (e.g., _Pytorch_, _Tensorflow_, _Chromium_, _LLVM_, _Qemu_, _Gstreamer_, ...) are already adopting it, I expect it to be more flexible and encourage participation in multiple initiatives (eg., add-on projects).

## My proposal: 

For example, I propose a management structure of main-repo (core) and sub-repos (add-on/sub-component/etc) after creating an org/accunt called "**fauxpilot**" as follows. :)

* Before: 
   * https://github.com/moyix/
   * https://github.com/moyix/fauxpilot (just one repo with personal account name)

* After (Draft): 
  * https://github.com/fauxpilot
  * Main repos
    * https://github.com/fauxpilot/fauxpilot (main repo)
  * Sub repos
    * https://github.com/fauxpilot/fauxpilot.github.io (main homepage repo for https://fauxpilot.gitnub.io)
    * https://github.com/fauxpilot/tools (development tools such as training, fine-tunging, inferencing, optimation)
    * https://github.com/fauxpilot/addon (extra features to help fauxpilot users)
        ... and so on ...
		
		
BRs, 
Geunsik Lim.

**Comment by azeemba** [comment]
I think this is an interesting idea and probably should be considered as more tools and addons become available. When that happens, it will be useful to pull in everything under an org for discoverability.

However, @leemgs I think you should consider deleting the org at https://github.com/fauxpilot. Currently it will only lead to confusion because when people search for "fauxpilot", they will almost certainly want to find moyix/fauxpilot.

**Comment by leemgs** [comment]
You are correct. I removed https://github.com/fauxpilot to prevent an unexpected confusion over FauxPilot.
* before:  https://github.com/fauxpilot/ (removed)
* after   :  https://github.com/fauxpilot-addon/

**Comment by moyix** [comment]
Thanks! I have created an org there now and moved the repo so that it's not all tied to my account :) We can work on making a landing page and think about hosting things like a VSCode plugin or web interface under that org.
