### ISSUE TITLE
Can you share your server?I want it but I haven't got a computer was eligible.

### ISSUE THREAD

**Issue by smart2pet** [fauxpilot/fauxpilot#120]

**Comment by wzy-99** [comment]
greedy

**Comment by fdegier** [comment]
The intent of FauxPilot is to run your own server so your code remains private, FauxPilot is not hosting an instance of FauxPilot for public use.

**Comment by smart2pet** [comment]
Ok. I know about it. I think that's why we use FauxPilot not GitHub Copilot. Github Copilot collects personal code to train models.
