### ISSUE TITLE
[feature request] basic gitlab setup instructions 


### ISSUE THREAD

**Issue by Tom-Neverwinter** [fauxpilot/fauxpilot#139]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example, I'm always frustrated when [...]

No. 

**Describe the solution you'd like**

Basic install instructions using gitlab

**Describe alternatives you've considered**

Digging through the listed group for setup instructions. (none found, however lots of useful details for when it does run such as how many tokens. Stops etc.) 

**Additional context**

None. Keep up the amazing work!

**Comment by fdegier** [comment]
Could you elaborate what you mean with `Basic install instructions using gitlab`, do you mean the GitLab VS Code extension?

**Comment by fdegier** [comment]
GitLab VS Code extension has dropped support for FauxPilot in v3.57.3 hence why you don't see the options. You could use v3.57.2 which still supports FauxPilot.
