### ISSUE TITLE
failed to connect to all addresses

### ISSUE THREAD

**Issue by panw3i** [fauxpilot/fauxpilot#152]
```
copilot_proxy_1  | [StatusCode.UNAVAILABLE] failed to connect to all addresses
copilot_proxy_1  | WARNING: Model 'fastertransformer' is not available. Please ensure that `model` is set to either 'fastertransformer' or 'py-model' depending on your installation
copilot_proxy_1  | Returned completion in 2524.986743927002 ms
copilot_proxy_1  | INFO:     2023-02-20 01:58:54,918 :: 172.18.0.1:32972 - "POST /v1/engines/codegen/completions HTTP/1.0" 200 OK
```

**Comment by thakkarparth007** [comment]
Hi @panw3i looks like you've installed the python version (guessing based on the error message and the latency). In that case, you must set the "model" argument to `py-model` instead of `fastertransformer` (which is the default).

**Comment by panw3i** [comment]
3Q

**Comment by 583175694** [comment]
> Hi @panw3i looks like you've installed the python based model (guessing based on the error message and the latency). In that case, you must set the "model" argument to `py-model` instead of `fastertransformer` (which is the default).
> 
> Assuming you're using the FastAPI UI for making the request, please double check the request body and set `model` to py-model.

The editor I use is vscode, where can I set the model to py-model?

**Comment by Venthe** [comment]
@583175694 Which VSCode extension do you use?

**Comment by matbgn** [comment]
Same here with VSCodium extension https://github.com/Venthe/vscode-fauxpilot

Set up with model `py-model`
