### ISSUE TITLE
My inference time is over 40 seconds on an rtx 2060 12gb with codegen 2B. Is this normal?

### ISSUE THREAD

**Issue by AndreyRGW** [fauxpilot/fauxpilot#155]

**Comment by thakkarparth007** [comment]
That doesn't seem normal. What's the context length? How many tokens are you asking for output? Are you using fastertransformer backend or python backend?

**Comment by AndreyRGW** [comment]
> That doesn't seem normal. What's the context length? How many tokens are you asking for output? Are you using fastertransformer backend or python backend?

I'm using fastertransformer and fauxpilot through copilot proxy.

**Comment by thakkarparth007** [comment]
Is this resolved? Would be great if you could summarize what fixed it for future users who might face this.
