### ISSUE TITLE
Does fauxpilot support adding our own data set for finetuning？ Thank you！

### ISSUE THREAD

**Issue by whitesay** [fauxpilot/fauxpilot#193]
I want to add my own language for fauxpilot training. Do you support fine tuning training now？

**Comment by jamesford42** [comment]
I second this question.

**Comment by thakkarparth007** [comment]
Fauxpilot is not a training framework. It's an inference framework. You can of course finetune the codegen model on any data and then load that model into Fauxpilot. But there's no explicit script included that can help with doing the finetuning.
