### ISSUE TITLE
I try to use VSCode Copilot plugin by edit settings.json, but it seems that no requests have been sent to my local server

### ISSUE THREAD

**Issue by newrayray** [fauxpilot/fauxpilot#194]
I add this into settings,json
```
    "github.copilot.advanced": {
        "debug.overrideEngine": "codegen",
        "debug.testOverrideProxyUrl": "http://localhost:5000",
        "debug.overrideProxyUrl": "http://localhost:5000"
    }
```
the plugin doesnt work, and I'm sure that the server has been launched.

**Comment by andreybond** [comment]
Second that ^^^

I have fauxpilot server running in docker, I can see results returned when using REST interface via curl, but I can not see any requests from FauxPilot VsCode plugin. 

Any suggestions?

**Comment by newrayray** [comment]
> For the official copilot extension, you have to edit the src/extension.js file of the extension (it is located in your users folder in a .vscode/extensions folder) and replace all https://api.github.com/ and https://copilot-proxy.githubusercontent.com/ with http://yourip:5000/

It works

**Comment by wh5a** [comment]
@wrapss @newrayray Is the github copilot extension open source? I couldn't see the src/extension.js file, but I did see a dist/extension.js file. I applied the replacement there, and I can see it tried to connect to 127.0.0.1 but failed. Any ideas?

GitHub Copilot could not connect to server. Extension activation failed: "connect ECONNREFUSED 127.0.0.1:5000"

**Comment by monkeycraps** [comment]
> @wrapss @newrayray Is the github copilot extension open source? I couldn't see the src/extension.js file, but I did see a dist/extension.js file. I applied the replacement there, and I can see it tried to connect to 127.0.0.1 but failed. Any ideas?
> 
> GitHub Copilot could not connect to server. Extension activation failed: "connect ECONNREFUSED 127.0.0.1:5000"
> 
> I was able to follow the steps using OpenAI API though.

use local domain to request, it works for me
